#!/usr/bin/env bash

config=bashistrano_conf.sh

source "$config"

command=${1:-main} # Default to a command called "main"

user_commands=$(find . -name "*.sh" | grep -v "$config" | xargs cat)

for server in $servers
do
    ssh -T ${user}@${server} <<-EOF
        PATH=/usr/bin:/usr/local/bin:/bin
        # Make some vars available to user commands
        cmd_host=${HOSTNAME}
        cmd_user=${USER}

        # Make user's own config available to user commands
        $(cat $config)

        # Make some helper functions available to user commands
        prnt () {
            # TODO Get colours to work?
            local cyan=$(tput setaf 6)
            local clear=$(tput clear)
            echo "${cyan}[${user}@${server}]${clear} \$1"
        }

        # Default command, can be redefined by user
        main () {
            prnt "Hello, world"
        }

        prnt "Connected"

        # Define all user commands
        $user_commands

        prnt "Running '$command' on $server"
        $command
EOF
done
